# Generated by Django 3.1.4 on 2020-12-19 10:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Your 10 digit Indian (+91) Contact Number', max_length=31)),
                ('password', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
