# Generated by Django 3.1.4 on 2020-12-22 19:09

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20201220_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(default='images/dashboard-default-avatar2.png', upload_to=customer.models.upload_image),
        ),
    ]
