# Generated by Django 3.1.4 on 2020-12-23 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201223_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
